### ISSUE TITLE
would it be possible to get smartplaylists into the playlist tab?

### ISSUE THREAD

**Issue by lachlan-00** [antoniotari/reactive-ampache#2]
Hi,

I'd really like to see more development in ampache and this library/power ampache is really great.

I see there are playlists but not smart playlists, is that going to be possible to grab? if the API doesn't support it i'd like to look at getting that in there.

Power ampache seems to have trouble with large playlists over a certain number is there any way i can help with that too?

I'm trying to push ampache development further but i also have a fork that i'm running as a music-only ampache until development moves forward.

**Comment by lachlan-00** [comment]
Scratch that, i'm putting it in soon.

**Comment by antoniotari** [comment]
hey @lachlan-00 for some reason your messages ended up in my spam folder,where you able to make the changes you mentioned?

**Comment by lachlan-00** [comment]
smartplaylists are in develop if you have a number/limit set. The api is going to need a bit of work to it before moving the new version into stable..

I'm in the process of updating the subsonic api but then xml api after that. The current pull for subsonic enables token auth based on the api key and i think something similar would be good for the api.

**Comment by antoniotari** [comment]
hello, did you manage to finish the fix?

**Comment by lachlan-00** [comment]
Hey, I'd forgotten about this issue but the smart lists and API are functional.

I had just recently put in the ability to hide searches from playlist calls as well.

These are all available in power Ampache which I use for testing.

**Comment by lachlan-00** [comment]
I've been documenting things on the .org site. (Latest stable is 4.3) http://ampache.org/api/versions/api-4.3/

For 4.4 I've set a timer for 5th March for release. This won't change much more in the API compared to current stable besides a few fixes on properties and calls that were fixed in develop.

**Comment by lachlan-00** [comment]
- I also realise from reading the initial issue this was before I took over Ampache so all the points I raised after resolved
